Remove old networking API
theseus-os/Theseus pull request #1011
Opened 2023-07-20 03:43 UTC by tsoutsman

Also implicitly updates to `smoltcp v0.10` by removing the patch which brings some nice changes to error handling.

I've made some changes to `virtual_nic` and would like to run `test_ixgbe` but I'm unable to emulate an `ixgbe82599` NIC as [QEMU doesn't support it](https://en.wikibooks.org/wiki/QEMU/Devices/Network).

2023-07-20 04:41 UTC, tsoutsman commented on kernel/net/src/device.rs
> +        // data structures (e.g. `Vec`).
bump

2023-07-20 05:32 UTC, tsoutsman commented on kernel/net/src/device.rs
> +                // data structures (e.g. `Vec`).
bump

2023-07-21 21:43 UTC, kevinaboos requested changes

2023-07-21 21:43 UTC, kevinaboos commented on kernel/device_manager/src/lib.rs
> -const DEFAULT_GATEWAY_IP: [u8; 4] = [10, 0, 2, 2]; // the default QEMU user-slirp networking gateway IP
if this stuff is no longer required, that'd be awesome. Does smoltcp now support DHCP by default, or if not, where else are we defining the gateway IP for smoltcp to use?

2023-07-21 21:43 UTC, kevinaboos commented on kernel/net/src/device.rs
> +                // data structures (e.g. `Vec`).
resolved in discussion, panicking here is clearer than within `TransmitBuffer::new()`

2023-07-21 21:43 UTC, kevinaboos commented on kernel/e1000/src/lib.rs
> +            |interface| {
I actually think the old way was clearer and easier to grep for / understand. You can just make that function return OK unconditionally

2023-07-21 21:43 UTC, kevinaboos commented on kernel/net/src/device.rs
> +pub trait NetworkDevice: Send + Sync {
Is Any no longer needed? Is there another means of downcasting this kind of trait object?

2023-07-21 21:43 UTC, kevinaboos commented on old_crates/ethernet_smoltcp_device/Cargo.toml
I don't think there's any real reason to keep these crates, you can just delete em.

2023-07-21 21:43 UTC, kevinaboos commented
> I've made some changes to `virtual_nic` and would like to run `test_ixgbe` but I'm unable to emulate an `ixgbe82599` NIC as [QEMU doesn't support it](https://en.wikibooks.org/wiki/QEMU/Devices/Network).

@Ramla-I would you be able to test this IXGBE changeset for us? or do you have access to hardware with an IXGBE card?

2023-07-21 22:02 UTC, Ramla-I commented
> > I've made some changes to `virtual_nic` and would like to run `test_ixgbe` but I'm unable to emulate an `ixgbe82599` NIC as [QEMU doesn't support it](https://en.wikibooks.org/wiki/QEMU/Devices/Network).
> 
> @Ramla-I would you be able to test this IXGBE changeset for us? or do you have access to hardware with an IXGBE card?

Yes I do. I can test it. I just need to check that the ixgbe rx/tx is still working when using the virtual nic interface, right?

2023-07-22 00:35 UTC, kevinaboos commented
> Yes I do. I can test it. I just need to check that the ixgbe rx/tx is still working when using the virtual nic interface, right?

Great, thanks! Yes, that's correct, just whatever networking tests you normally do. `ping`, at a bare minimum.

2023-07-23 10:51 UTC, tsoutsman commented on kernel/net/src/device.rs
> +pub trait NetworkDevice: Send + Sync {
No, I'm pretty sure it was a leftover from a previous version of the net API. I just forgot to remove the bound previously.

2023-07-23 11:22 UTC, tsoutsman commented on kernel/device_manager/src/lib.rs
> -const DEFAULT_GATEWAY_IP: [u8; 4] = [10, 0, 2, 2]; // the default QEMU user-slirp networking gateway IP
> Does smoltcp now support DHCP by default

Yes, but it's not as simple as creating a DHCP socket and polling the interface as that returns [`Event::Deconfigured`](https://docs.rs/smoltcp/latest/smoltcp/socket/dhcpv4/enum.Event.html).

I'll look into it more but I think it's best left for a future PR.

> where else are we defining the gateway IP for smoltcp to use?

`net/src/lib.rs`

2023-07-24 17:35 UTC, kevinaboos commented on kernel/device_manager/src/lib.rs
> -const DEFAULT_GATEWAY_IP: [u8; 4] = [10, 0, 2, 2]; // the default QEMU user-slirp networking gateway IP
Ok great, I missed that those IP addrs were already moved into `net` in a previous changeset; I was looking for them as part of this PR.

2023-07-24 19:13 UTC, kevinaboos approved these changes
Gonna go ahead and approve/merge this PR; if `ixgbe` testing turns up an error we can address that separately.

Regarding the comment about #587, I don't think that's too likely to actually happen, but it's noted that this removes one of those patches, which is nice for myriad other reasons.

Also see my discussion starter about the design of the `NetworkDevice` trait on discord #networking.

2023-07-24 19:15 UTC, merged