PCI & interrupts modifications related to USB
theseus-os/Theseus pull request #1071
Opened 2023-11-08 17:02 UTC by NathanRoyer

These are changes that are indirectly related to the USB PR.

2023-11-22 00:23 UTC, kevinaboos requested changes
Looks good mostly, just some small requests.

One comment/question about RwLocks -- they are inefficient and much slower than Mutexes, so they're typically only used when absolutely necessary. It appears that the RwLock around `INTX_DEVICES` _might_ be necessary, but I can't tell for sure. If the point of using a RwLock there is to allow multiple interrupt handlers to access it simultaneously, then that is kind of defeated by using the interrupt-safe RwLock variant, which prevents other interrupts from firing while it is held.

What about the RwLock around the PciDevice's `Waker`? Are there any use cases where multiple tasks need to immutably access that waker concurrently?

2023-11-22 00:23 UTC, kevinaboos commented on kernel/interrupts/src/aarch64/mod.rs
> +pub fn init_pci_interrupts(handler: InterruptHandler) -> Result<(), &'static str> {
Need some docs about what this function does. I presume it registers the given `handler` to all legacy PCI interrupt vectors, but it's better to be clear.

Also, on that note, do we always want the same single interrupt handler to be registered for all PCI interrupts? It's probably better to allow the caller to specify individual handlers for each of the 4 legacy interrupts, e.g., 

```rust
pub fn init_pci_interrupts(
    pin_a_handler: InterruptHandler,
    pin_b_handler: InterruptHandler,
    pin_c_handler: InterruptHandler,
    pin_d_handler: InterruptHandler,
) -> Result<(), &'static str> {
```

2023-11-22 00:23 UTC, kevinaboos commented on kernel/interrupts/src/aarch64/mod.rs
> +                return Err("A different interrupt handler has already been setup for that IPI");
outdated error msg

2023-11-22 00:23 UTC, kevinaboos commented on kernel/pci/src/lib.rs
> +// Aarch64-only because legacy interrupts aren't supported on x86
just clarifying your comment, which made it sound like x86 itself doesn't support this 
```suggestion
// Currently aarch64-only, because legacy interrupts aren't supported on x86 yet.
```

2023-11-22 00:23 UTC, kevinaboos commented on kernel/pci/src/lib.rs
> +    /// Sets a a task waker to be used when this device triggers an interrupt
typo: repeated word "a"

2023-11-22 00:23 UTC, kevinaboos commented on kernel/pci/src/lib.rs
> +//! https://electronics.stackexchange.com/a/343218
rustdoc wants you to surround raw links with `<` `>`
```suggestion
//! <https://electronics.stackexchange.com/a/343218>
```

Also, while this link is nice, it's not really anything official. Is there a more official source, such as a chapter/section of the PCI spec or an intel/arm technical reference manual?

2023-12-06 13:45 UTC, NathanRoyer commented
> If those are not needed, then you should switch to Mutex.

You were right; I replaced these with Mutexes.

2023-12-12 08:43 UTC, kevinaboos approved these changes
Accepting for now, but please see the 3 comments I left. Two of them can be addressed quickly with a follow-up PR or as part of another PR.

2023-12-12 08:43 UTC, kevinaboos commented on kernel/pci/src/lib.rs
> +    pub fn pci_set_interrupt_disable_bit(&self, bit: bool) {
I think we should rename this function to be more clear about what it actually does, and use the standard "enable_xyz" terminology. We can mention what it actually does (i.e., set the disable bit) in the function documentation, but as it stands now it's quite difficult to understand. 

I'll accept this now; kindly include that in the next PR about PCI/USB. 👍

2023-12-12 08:43 UTC, kevinaboos commented on kernel/pci/src/lib.rs
> +                None => log::error!("Device doesn't have an interrupt waker!"),
i changed this to an error since i don't think it merits a panic, and also, panicking inside an interrupt handler should ideally be avoided.

2023-12-12 08:43 UTC, kevinaboos commented on kernel/pci/src/lib.rs
> +            device.pci_enable_interrupts(false);
this is also confusing, as upon first glance, the reader of this code would expect that you're just temporarily disabling PCI interrupts here while you handle the interrupt and then re-enabling them later. However, that doesn't happen, so this must mean something else.

We should rename and properly document the `pci_enable_interrupts()` function to be more clear about how and why it should be invoked (e.g., perhaps we just always want to disable this type of interrupt?)

2023-12-12 08:47 UTC, merged