Arm uefi
theseus-os/Theseus pull request #179
Opened 2019-07-24 10:07 UTC by snoword

Port Theseus to ARM
Initialize memories, exceptions and logs

2019-07-26 07:42 UTC, kevinaboos requested changes
You've added a lot of new crates, of course, but some of them don't appear to be necessary. Mainly, things having to do with volatile types (`tock-registers`, `vcell`, `volatile-registers`, etc) can all be replaced by the `volatile` crate that we already use, which has types like `ReadOnly`, `ReadWrite`, and `WriteOnly`. Were you using those directly, or were they dependencies of other crates you're using? 

So, in general, you seem to have basically put aarch-specific stuff in like.. dozens of crates. That's really quite messy, and makes it even more difficult to add additional architectures in the future. What I was hoping for is that you'd separate the x86-specific stuff and the arm-specific stuff into separate crates, or something like that. Making _every_ crate need to be aware of the underlying architecture is surely a recipe for an unmaintainable mess.
For example, the interrupts and exceptions crates are just littered with cfg blocks, and I cannot accepts something like that into the mainline. 

Also, a note about the cfg blocks -- we don't support x86 (32-bit) and never intend to, so you don't need to insert that as an `any` condition everywhere. It's also not necessarily correct, a lot of those crates do _not_ support 32-bit x86, they only support x86_64. 

So far I have only reviewed up to the `memory` crate. I will post more comments later.

2019-07-26 07:42 UTC, kevinaboos commented on applications/terminal/Cargo.toml
> +
this is just some old leftover junk, the terminal shouldn't and doesn't need x86_64 or aarch64 stuff, you can remove these.

2019-07-26 07:42 UTC, kevinaboos commented on applications/terminal_print/Cargo.toml
> +
same thing as above, none of these are needed.

2019-07-26 07:42 UTC, kevinaboos commented on cfg/aarch64-theseus.json
> +  "llvm-target": "aarch64-pc-windows-msvc",
is this the right target triple, `pc-windows-msvc`? Doesn't it need to be `none`, and shouldn't we be using a gnu platform instead of microsoft?

2019-07-26 07:42 UTC, kevinaboos commented on kernel/fs_node/Cargo.toml
> +
remove, `fs_node` doesn't need arch stuff.

2019-07-26 07:42 UTC, kevinaboos commented on kernel/memfs/Cargo.toml
> +
memfs doesn't need x86 either

2019-07-26 17:19 UTC, kevinaboos requested changes
Please undo all of these unnecessary formatting and whitespace changes. This makes it impossible to determine what actually changed to accommodate ARM and what was unnecessary.

In fact, I'm going to postpone the rest of my review until you address this. Thanks.

2019-07-31 05:03 UTC, snoword commented on applications/terminal/Cargo.toml
> +
removed

2019-07-31 05:03 UTC, snoword commented on applications/terminal_print/Cargo.toml
> +
removed

2019-07-31 05:03 UTC, snoword commented on cfg/aarch64-theseus.json
> +  "llvm-target": "aarch64-pc-windows-msvc",
This indicates that the project will be compiled as a UEFI application(UEFI applications can run on Windows). GNU will use a chainloader to load the UEFI binary file

2019-08-01 23:03 UTC, snoword commented on kernel/fs_node/Cargo.toml
> +
solved

2019-08-06 20:55 UTC, snoword commented on kernel/memfs/Cargo.toml
> +
deleted

2019-08-09 00:18 UTC, snoword commented on applications/terminal/Cargo.toml
> +
vcell, volatile-registers are introduces by the ARM64 crate `cortex-m`.
I have removed tock-registers.

2021-02-11 16:38 UTC, closed without merging