Intel cat
theseus-os/Theseus pull request #308
Opened 2020-07-23 19:13 UTC by jacob-earle

Implementing basic functionality for controlling Intel CAT: partitioning the cache into exclusive regions and assigning groups of tasks to use those cache regions.

2020-07-23 22:47 UTC, NamiLiy requested changes

2020-07-23 22:47 UTC, NamiLiy commented on applications/test_intel_cat/src/lib.rs
> +
At the beginning of the code have the following segment

```
#[cfg(not(use_intel_cat))]
{
    println("Intel cat is not enabled. No tests will be run. Compile with use_intel_cat to run these tests");
   return 0;
}
```

2020-07-23 22:47 UTC, NamiLiy commented on kernel/intel_cat/src/lib.rs
> +    pub descriptor_list: Vec<ClosDescriptor>,
Add comment to each field

2020-07-23 22:47 UTC, NamiLiy commented on kernel/intel_cat/src/lib.rs
> +fn get_free_closid() -> Result<u16, &'static str>{
/// instead of //

2020-07-23 22:47 UTC, NamiLiy commented on kernel/intel_cat/src/lib.rs
> +    0x7ff & (!exclusive_region)
Add
`// 0x7ff is the size of the bitmask`

2020-07-23 22:47 UTC, NamiLiy commented on kernel/intel_cat/src/lib.rs
> +        let taskref = spawn::new_task_builder(set_clos_on_single_core, CURRENT_CLOS_LIST.lock().clone())
indentation looks wierd

2020-07-23 22:47 UTC, NamiLiy commented on kernel/intel_cat/src/lib.rs
> +pub fn reset_cache_allocations() -> Result<(), &'static str>{
This code has a small corner case I think. Let me think more about it

2020-07-23 22:47 UTC, NamiLiy commented on kernel/intel_cat/src/lib.rs
> +pub fn reset_cache_allocations() -> Result<(), &'static str>{
Okay this  would work fine after clos are reset. 
But would fail if we try to allocate exclusive space again. (The space we allocated will not be exclusive to previous iterations allocation)
We should iterate the task list and reset the closids of each task to zero as well.

```
for (id, taskref) in task::TASKLIST.lock().iter() {
   taskref.set_closid = 0;
}
```

2020-07-27 19:11 UTC, NamiLiy commented on applications/test_intel_cat/src/lib.rs
> +	{
The indentation still looks weird around here

2020-07-27 19:11 UTC, NamiLiy commented on applications/test_intel_cat/src/lib.rs
> +		match set_closid_on_current_task(256){
indentation

2020-07-27 23:42 UTC, NamiLiy reviewed
Change inline assembly code to Rust unsafe code

2020-07-27 23:42 UTC, NamiLiy commented on kernel/intel_cat/src/lib.rs
> +    let msr : u32 = IA32_L3_CBM_BASE + clos.closid.0 as u32;
Can we replace this inline assembly section with rust unsafe code.

`use x86_64::registers::msr::*;` at the top.

```
let msr : u32 = MSR_W_PMON_EVNT_SEL0 + clos.closid.0 as u32;
unsafe { wrmsr(msr, clos.bitmask); }
```

Double check my msr calculation and retest the code on the machine.

2020-07-28 17:03 UTC, jacob-earle commented on kernel/intel_cat/src/lib.rs
> +    let msr : u32 = IA32_L3_CBM_BASE + clos.closid.0 as u32;
Done, although I kept the name IA32_L3_CBM_BASE to conform to the naming standards used in the Intel software manual.

2020-07-28 17:07 UTC, jacob-earle commented on applications/test_intel_cat/src/lib.rs
> +	{
Fixed, I indented everything inside the config block

2020-07-28 17:15 UTC, jacob-earle commented on applications/test_intel_cat/src/lib.rs
> +		match set_closid_on_current_task(256){
I think I fixed this one, I didn't see anything off on my machine, so I'll have to see when I push again

2020-07-28 17:45 UTC, NamiLiy commented on kernel/closid_settings/src/lib.rs
> +#![no_std]
Add a small top level description for this crate.

2020-07-28 17:51 UTC, jacob-earle commented on kernel/closid_settings/src/lib.rs
> +#![no_std]
Done

2020-08-20 16:19 UTC, NamiLiy reviewed
Minor corrections

2020-08-20 16:19 UTC, NamiLiy commented on applications/test_intel_cat/src/lib.rs
> +			Err(_) => {
Same

2020-08-20 20:18 UTC, jacob-earle commented on applications/test_intel_cat/src/lib.rs
> +			Err(_) => {
Same as above.

2021-04-14 19:11 UTC, kevinaboos commented
Closing because we no longer want CAT support in the mainline. This PR is also outdated & incompatible as it originated from the older private Theseus repo.

2021-04-14 19:11 UTC, closed without merging