Cortex-m4 Logging
theseus-os/Theseus pull request #403
Opened 2021-07-01 20:15 UTC by jacob-earle

Adding logging functionality over the UART on the STM32F4-Discovery board (excludes changes necessary to run Theseus on ARM boards)

2021-08-11 06:25 UTC, Acciente717 reviewed
Great work! All looks good to me.

2021-08-11 08:19 UTC, kevinaboos requested changes
Thanks @jacob-earle and @Acciente717. Looks good in general! 

Let's discuss the crate organization on Slack; for example, I think the `uart` module should be its own crate.

Also, kindly remove the addition of the `irq_safety` module from `libs/` and submit a separate PR against that repo so we can add arm support to it. There shouldn't really be any code duplication needed there except for the part about held interrupts.

2021-08-11 08:19 UTC, kevinaboos commented on kernel/boards/src/lib.rs
> +//! This crate does not implement any functionality itself, but instead contains a subcrate that implements the platform-specific functionality for each ARM microcontroller we support.
Needs line breaks

2021-08-11 08:19 UTC, kevinaboos commented on kernel/boards/Cargo.toml
> +# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
Remove

2021-08-11 08:19 UTC, kevinaboos commented on kernel/boards/Cargo.toml
> +authors = ["Jacob Earle <jacob.earle@yale.edu>"]
Add brief `description`

2021-08-11 08:19 UTC, kevinaboos commented on kernel/boards/stm32f4_discovery/Cargo.toml
> +# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
Remove.

Add `description`

2021-08-11 08:19 UTC, kevinaboos commented on kernel/boards/stm32f4_discovery/src/lib.rs
> +//! Implements platform specific functionalities for the STM32F4_Discovery board, exposing its peripherals and providing ways of interacting with them.
Line breaks

2021-08-11 08:19 UTC, kevinaboos commented on kernel/boards/stm32f4_discovery/src/lib.rs
> +    }
Use the `todo!` or `unimplemented! ` macro here, whichever is appropriate

2021-08-11 08:19 UTC, kevinaboos commented on kernel/boards/stm32f4_discovery/src/uart/mod.rs
> +// /// Macro used to print a formatted string over a serial port on the UART
Is this old? If so, remove.

2021-08-11 08:19 UTC, kevinaboos commented on kernel/logger/Cargo.toml
> +path = "../../libs/irq_safety"
This is outdated I think

2021-08-11 08:19 UTC, kevinaboos commented on kernel/serial_port/serial_port_x86/Cargo.toml
> +[dependencies.irq_safety]
This doesn't exist, use the git dependency

2021-08-11 17:30 UTC, kevinaboos commented on Makefile
> +		-kernel target/thumbv7em-none-eabi/theseus.bin
for these targets, kindly use the existing Makefile variables in order to standardize targets across the whole build system.  For example, look at the x86_64 invocation of cargo:
```
	RUST_TARGET_PATH="$(CFG_DIR)" RUSTFLAGS="$(RUSTFLAGS)" cargo build $(CARGOFLAGS) $(BUILD_STD_CARGOFLAGS) $(RUST_FEATURES) --all --target $(TARGET)
```
Here you'll just set the proper variables for `TARGET` and also change `--all` to `-p nano_core`

2021-08-11 17:35 UTC, kevinaboos commented on kernel/boards/stm32f4_discovery/src/uart/mod.rs
> +pub fn uart_init(uart_address: *const usart1::RegisterBlock) {
a safe function cannot accept an arbitrary pointer and then dereference it. This either has to be marked as unsafe (which is undesirable IMO) or accept a different argument such as a reference to or an owned instance of the `RegisterBlock` type

2021-08-11 17:38 UTC, kevinaboos commented on kernel/boards/stm32f4_discovery/src/uart/mod.rs
> +    uart_address: *const usart1::RegisterBlock,
Do we need to store raw pointers everywhere? Can we not obtain an instance of `usart1::RegisterBlock` or at least a reference to it? (Sorry if dumb, i'm not familiar with the svd2rust APIs)

2021-08-11 17:38 UTC, kevinaboos commented on kernel/boards/stm32f4_discovery/src/uart/mod.rs
> +unsafe impl Send for SerialPort {}
this is almost always a bad idea, unless you're implementing a mutual exclusion type yourself.

2021-08-11 17:39 UTC, kevinaboos commented on kernel/serial_port/serial_port_arm/Cargo.toml
> +# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
remove

2021-08-11 17:40 UTC, kevinaboos commented on kernel/serial_port/serial_port_arm/src/lib.rs
> +    // Dummy implementation for when no physical device is present, in which case semihosting will be used
Please add a block of crate-level documentation explaining what semihosting is and why the complex target_vendor-specific configuration is required here.

2021-08-11 17:42 UTC, kevinaboos commented on kernel/serial_port/serial_port_x86/src/lib.rs
> +//! Support for basic serial port access, including initialization, transmit, and receive.
In this file, there is now a strange mix of 2-space tabs and actual tab characters. In keeping with the rest of the project, please use 4-space tab indentation, as it was before.

2021-08-11 17:44 UTC, kevinaboos commented on kernel/serial_port/src/lib.rs
> +//! This crate provides an abstraction on top of the separate serial port implementations for x86 and ARM, located in `./serial_port_x86` and `./serial_port_arm`.
Excellent job with this crate! This is exactly the kind of abstraction I was envisioning. 

We could strengthen it further with a serial port trait to guarantee that all arch-specific implementations provide the same API, but that can be done in the next PR.

2022-03-25 17:47 UTC, kevinaboos requested changes
Re-reviewing since some changes have been made.

- the `TriState` concept is unnecessarily duplicated, let's move it up a level into a common entity
- there seems to actually be 3 types of support for serial ports now: x86, arm (stm device), and arm semihosting. The crate/module structure should reflect that instead of stuffing the semihosting code into the top-level `lib.rs` file in serial_port_basic_arm
- Some Serial port-related code is actually in `kernel/boards/stm.../src/uart/mod.rs`, which is quite confusing. Not sure why that code is there instead of in a serial port crate. Is there a true distinguishable difference between UART/USART on arm and a serial port on arm?
- Is there only a single serial port / UART device on all ARM devices? If so, do you need the `SerialPortAddress` enum concept?
- There's an API mismatch between the x86 serial port basic and the arm ones. You've covered the implementation of `fmt::Write`, but that's pretty much it. It might be worthwhile to introduce a top-level `SerialPortTrait` that defines the minimal set of functions that each arch-specific Serial Port instance should implement, in order to ensure API completeness and matching.

2022-07-20 23:42 UTC, kevinaboos commented
Closing due to inactivity and the fact that the Cortex-M4 port will likely not be upstreamed.

2022-07-20 23:42 UTC, closed without merging