Fix: Overflow in TSC (Timestamp counter)
theseus-os/Theseus pull request #441
Opened 2021-08-26 14:08 UTC by Narasimha1997

Fixed the panic due to overflow of 64-bit unsigned integer by extending the size to 128 bits. The changes are reflected on `kernel/tsc/src/lib.rs`, also the `kernel/libterm` crate depends on the value from timestamp counter for some internal calculation, so the necessary changes are also made in this crate (updated the size of blinking frequency from 64 to 128 bits).

2021-08-26 20:34 UTC, kevinaboos commented
Thanks for the PR, @Narasimha1997! This does seem to address the issue partially, but it doesn't really fix the core problem of overflow possibly occurring. I realize overflow is highly unlikely with a 128-bit integer, but we might as well address that possibility now. 

For that, we'd need to use some kind of overflow-aware mathematical operation, e.g., wrapping, saturating, or a checked multiplication/addition operation in all functions that operate on TSC values. A checked operation would probably be my recommendation, unless you had compelling reasons to use wrapping ones instead. Let me know what you think.

2021-08-27 01:51 UTC, Narasimha1997 commented
@kevinaboos 
Yes, we can use `checked_mul` in `to_ns` function of `TscTicks` and keep `u128` as it is. Anyways the `to_ns` is gonna return an option, so it returns `None` in case of overflow. This the only place I see where overflow check is required right now.

2021-08-29 09:40 UTC, Narasimha1997 commented
@kevinaboos 
I have added `checked_mul` in the latest commit as discussed.

2021-08-30 17:31 UTC, kevinaboos requested changes
Looks good; I left one comment about code style. Ready to merge after that. :+1:

2021-08-30 17:31 UTC, kevinaboos commented on kernel/tsc/src/lib.rs
> +        }
Kindly update the docs as well to reflect the new conditions under which `None` may be returned. Also, let's stick with the combinator format, something like this:
```
get_tsc_frequency()
    .ok()
    .and_then(|freq| self.0.checked_mul(1000000000)
        .map(|checked_tsc| checked_tsc / freq)
    )
```

2021-08-31 08:36 UTC, Narasimha1997 commented
Made all the changes and rebased it to a single commit.

2021-08-31 17:34 UTC, kevinaboos commented
LGTM, I tested it and can confirm it works in debug build mode. Thanks again!

2021-08-31 17:36 UTC, kevinaboos approved these changes

2021-08-31 17:39 UTC, merged