Add new graphics layer
theseus-os/Theseus pull request #722
Opened 2022-12-09 12:36 UTC by ouz-a

# Porthole
Porthole, is new graphics layer for the Theseus OS, inspired by the old graphic's stack written from ground up Porthole has several goals:
- Make it easy to use.
- KISS (E.g; We won't write code that is going increase performance by %2 while making it harder to understand)
- Performance is high priority.
- It should be modular.

## Design
Detailed design of Porthole will be written here.

## Tasks:
- [X] Display pixels
- [X] Display text
- [X] Resizable windows
- [X] Create the initial PR
- [ ]  Handle keyboard
- [ ]  Handle rendering order
- [ ]  Error handling
- [ ]  Replace old graphics stack entirely.

_This is very early phase code most of the it going change after reviews/discussions_

2022-12-12 18:00 UTC, kevinaboos requested changes
Thanks! I left some comments; the biggest issue is the way that offset calculations and bounds checking happens on a per-pixel basis, sometimes more than once per pixel.

2022-12-12 18:00 UTC, kevinaboos commented on kernel/multicore_bringup/src/lib.rs
> +    pub width: u16,
these are private to avoid accidental modification; there are some accessor functions that you can use instead: https://www.theseus-os.com/Theseus/doc/multicore_bringup/struct.GraphicInfo.html#method.width

2022-12-12 18:00 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +        let some_slice = slice.as_bytes();
Is there a particular reason why you're converting the string to a byte slice here? I would think it's better to keep it as a string so you can more easily handle wide or multi-byte characters (e.g., emoji, other unicode chars). Reducing it to a byte slice removes important information.

2022-12-12 18:00 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +    fn init_front_buffer() -> Result<FrameBuffer, &'static str> {
I think it's a good idea to use two separate types for this:
1. A type to represent the real physical framebuffer (or framebuffers, in the case of double buffering) that is mapped to actual graphics memory
2. A type to represent virtual framebuffers that are just arbitrary chunks of memory

The idea is that, by design, we can prevent accidentally reading from a real framebuffer by not implementing functions that do that, like `get_pixel()`. Only the virtual framebuffer type would allow reading from it, while the real/physical framebuffer type would only allow writing to it.

2022-12-12 18:00 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +                    self.draw_something(x, y, 0xF123999);
one of the main goals of an API for drawing things should be to allow the callers to easily avoid the expensive bounds checks and calculations of pixel offsets on a per-pixel basis. Here, you're forcing that to occur not just once, but _twice_ per pixel, which is a lot of overhead. 

Instead of using indexing (which requires bound checking), use iterators.

2022-12-14 12:57 UTC, ouz-a commented on kernel/multicore_bringup/src/lib.rs
> +    pub width: u16,
fixed that

2022-12-14 12:59 UTC, ouz-a commented on applications/porthole/src/lib.rs
> +        let some_slice = slice.as_bytes();
That's how old api worked to support basic text displaying, supporting multi-byte characters is future work.

2022-12-29 18:03 UTC, kevinaboos requested changes
leaving a partial review to share notes

2022-12-29 18:03 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +    if let Some(title) = window.title.clone() {
this eagerly clones the whole `title` String every time. Instead move the `.clone()` operation into the inside of the branch

2022-12-29 18:03 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +    window: &mut MutexGuard<Window>,
I assume here you mean `&mut Window`, since there's no real reason to take a mutable reference to a `MutexGuard`. The only reason you'd pass a guard is if you needed the lock to be released within this function, and if that was the case, you'd need to pass it by ownership

2022-12-29 18:03 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +/// used for Window and WindowManager's backbuffer.
Note that in the future when we support true double buffering using graphics memory, this will not be true (and thus this type shouldn't be used to represent that backbuffer in graphics memory).

2022-12-29 18:03 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +        for (w_color, pixel) in w_it.zip(f) {
this is the right idea and, ultimately, the end point for what i was hoping to see once you have obtained an iterator over the window region (source) and an iterator over the framebuffer region (destination).

2022-12-29 18:03 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +        unsafe {
definitely no need to use unsafe here or anywhere else in this entire crate.

2022-12-29 18:03 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +    pub fn return_drawable_area(&self) -> Rect {
consider caching the values of rectangular bounding boxes for things like the title rectangle, drawable areas, etc, since they only need to change rarely upon a window resize action.
Then, when the window actually gets resized, you can recalculate them. A great design pattern for this is to use an `Option<Rect>` with an accessor function like `get_or_insert()`

2023-01-05 22:09 UTC, m-hugo reviewed
and you have many methods and fields that should be pub but aren't
or you could remove every pub if you don't care about modularity

2023-01-05 22:09 UTC, m-hugo commented on applications/porthole/src/lib.rs
> +    fn copy_windows_into_main_vbuffer(&mut self, window: &mut MutexGuard<Window>) {
this should really be a Window method
```suggestion
    fn copy_into_vbuffer(&mut self, vbuf: &mut VirtualFrameBuffer){
```

2023-01-09 04:37 UTC, kevinaboos commented on applications/porthole/src/lib.rs
> +    fn draw_unchecked(&mut self, x: isize, y: isize, col: Color) {
remove unsafety

2023-01-24 19:30 UTC, kevinaboos commented
Closing in favor of #823

2023-01-24 19:30 UTC, closed without merging