Context Switching Primitives for AArch64
theseus-os/Theseus pull request #744
Opened 2022-12-16 16:50 UTC by NathanRoyer

This draft PR contains "regular" context switching primitives for aarch64:

- the `context_switch_regular` function (same signature as on x86_64):
    - saves general pupose regs,
    - saves the current SP to an arbitrary address expected to be in x0 (= parameter `_prev_stack_pointer`),
    - installs the new one expected to be in x1 (= parameter `_next_stack_pointer_value`),
    - restores GP regs from the just-installed stack
- `create_stack` is a utility function which allocates a 16-page long initial task stack; you have to give it a function pointer (such as the address of `landing_pad`) which will be executed if you use `context_switch_regular` with that new stack.
- `landing_pad` is a "task" function which simply re-triggers a context switch to return to the original main task.

These are used in `main` just before infinite looping as a demonstration.

2023-01-03 19:07 UTC, kevinaboos requested changes
Looks good! 

Linux only saves/restores `x18` - `x29` on aarch64, which apparently corresponds to the set of callee-saved registers. If you change your implementation to that, does everything still work correctly?
https://github.com/torvalds/linux/blob/69b41ac87e4a664de78a395ff97166f0b2943210/arch/arm64/kernel/entry.S#L820

2023-01-03 19:07 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/src/lib.rs
> +            str x2, [x0, 0]
i'm not an expert on aarch64 asm, but can this just be `str x2, [x0]`?

2023-01-03 19:07 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/src/lib.rs
> +            // x30 stores the return address
let's also mention that `x30` is a synonym for `LR`, the link register.
Add that here and everywhere else `x30` is referenced. Alternatively would it be better to use `LR` directly since it more clearly denotes that it's different than all other `x*` general-purpose regs?

2023-01-03 19:07 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/Cargo.toml
> +authors = ["Kevin Boos <kevinaboos@gmail.com>", "Nathan Royer <nathan.royer.pro@gmail.com>"]
it's all you, haha
```suggestion
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>"]
```

2023-01-03 19:07 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/src/lib.rs
> +        self.x2 = value;
This is fine for now, but i think once we change the context struct to hold only callee-saved registers, we'd want to use the first one there (`x18`).

Also, I only called that function `set_first_register()` because the first register is `r15` on x86, which is actually the _last_ register possibly used in the calling convention on x86. Since aarch64 has so many registers, it doesn't really matter which one we use, but technically the _last_ one would be `x29`. Here, "last" means "the least likely one to be ever overwritten".

2023-01-03 19:07 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/src/lib.rs
> +        self.x2 = value;
So, really, we ought to use `x29` i think. Doesn't matter much between `x18` and `x29`, but yeah.

2023-01-04 14:00 UTC, NathanRoyer commented on aarch64/kernel/context_switch_regular/src/lib.rs
> +        self.x2 = value;
https://wiki.cdot.senecacollege.ca/wiki/AArch64_Register_and_Instruction_Quick_Start

I forgot about this but x29 is the "frame register" and apparently serves some special purpose. I'll use x28.

2023-01-04 14:30 UTC, NathanRoyer commented
> If you change your implementation to that, does everything still work correctly?

Indeed, it still works correctly :ok_hand:

2023-01-04 23:44 UTC, kevinaboos requested changes
Only a few nitpicks left, other than that it looks excellent.

2023-01-04 23:44 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/src/lib.rs
> +            sub sp,  sp,  #8 * 6 * 2
quite nitpicky, but i think it's clearer to say `#8 * 2 * N`, since it more clearly represents that you are saving an 8-byte register twice at the offset `N`.

2023-01-04 23:44 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/src/lib.rs
>              // Make room on the stack for the exception context.
is this an exception context? i think that's not quite accurate, it's a task's _execution_ context.

2023-01-04 23:44 UTC, kevinaboos commented on aarch64/kernel/nano_core/context_switch.rs
> +    let artificial_ctx_src = artificial_ctx.as_bytes();
we don't need `as_bytes()` here -- we can directly write the object itself to the region of memory as long as it implements `FromBytes`. Not only is that faster, but it's also more readable in terms of the code's intent.

Look at how we do it in `spawn::setup_context_trampoline()`

2023-01-04 23:44 UTC, kevinaboos commented on aarch64/kernel/context_switch_regular/Cargo.toml
> +description = "Context switching routines and structs for regular (non-SSE) register sets, aarch64 version"
nit
```suggestion
description = "Context switching routines and structs for regular (non-SIMD) tasks on aarch64"
```

2023-01-11 02:34 UTC, kevinaboos approved these changes

2023-01-11 02:37 UTC, merged