Add `mpmc_queue`
theseus-os/Theseus pull request #756
Opened 2022-12-20 08:46 UTC by tsoutsman

Unlike `mpmc`, this queue is unbounded. An unbounded `mpmc` queue is commonly used as a global fallback runqueue in schedulers. This PR is the first step in improving the round robin scheduler.

Signed-off-by: Klim Tsoutsman <klim@tsoutsman.com>

2022-12-20 13:32 UTC, tsoutsman commented
Was watching <https://www.youtube.com/watch?v=EY7Wi9fV5bk> in my spare time, and turns out it's directly relevant to the PR I just submitted :)

Miri was able to detect this so I guess there's another tool I should learn:
```
running 2 tests
test tests::test_mpmc_stress ... error: Undefined Behavior: trying to retag from <415901> for Unique permission at alloc150534[0x0], but that tag does not exist in the borrow stack for this location
    --> /home/klim/.rustup/toolchains/nightly-2022-11-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:2297:18
     |
2297 |             Some(v) => ControlFlow::Continue(v),
     |                  ^
     |                  |
     |                  trying to retag from <415901> for Unique permission at alloc150534[0x0], but that tag does not exist in the borrow stack for this location
     |                  this error occurs as part of retag at alloc150534[0x0..0x10]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
```

2022-12-28 19:09 UTC, kevinaboos requested changes
functionally it looks good. Left a few minor comments.

2022-12-28 19:09 UTC, kevinaboos commented on libs/mpmc_queue/src/lib.rs
> +    unsafe { NonNull::new_unchecked(item_pointer) }
I thought this pattern seemed unnecessarily unsafe, so I skimmed a few PRs on the rust-lang/rust repo and discovered that there used to be a `Box::into_raw_non_null()`. But it was never stabilized, and then deprecated and removed. The consensus was that the proper way to do this is:
```rust
    NonNull::from(Box::leak(item))
```

2022-12-28 19:09 UTC, kevinaboos commented on libs/mpmc_queue/src/lib.rs
> +            // SAEFTY: The only other pointer to the tail is stored in the second-to-last
```suggestion
            // SAFETY: The only other pointer to the tail is stored in the second-to-last
```

2022-12-28 19:09 UTC, kevinaboos commented on libs/mpmc_queue/src/lib.rs
> +            // SAEFTY: The only other pointer to the tail is stored in the second-to-last
```suggestion
            // SAFETY: The only other pointer to the tail is stored in the second-to-last
```

2022-12-28 19:09 UTC, kevinaboos commented on libs/mpmc_queue/src/lib.rs
> +        // SAFETY: current_head is a valid pointer.
i think `Box::from_raw()` also requires that the pointer was obtained from a `Box` originally, too. Obviously you ensure that via usage of `box_pointer()`, but I still think it merits an explicit comment here.

2022-12-28 19:09 UTC, kevinaboos commented on libs/mpmc_queue/src/lib.rs
> +        // SAFETY: current_head is a valid pointer.
specific details here: https://doc.rust-lang.org/std/boxed/index.html#memory-layout

so it's not that it had to come from a `Box`, but the fact that it came from a `Box` does satisfy the `Layout`-related invariants.

2022-12-29 01:19 UTC, kevinaboos approved these changes

2022-12-29 01:21 UTC, merged