Encapsulate ps2 functions (wip)
theseus-os/Theseus pull request #765
Opened 2022-12-23 10:12 UTC by hecatia-elegua

The only thing still unclear is how to pass the structs to their interrupt handlers.

2022-12-23 13:30 UTC, tsoutsman commented
> The only thing still unclear is how to pass the structs to their interrupt handlers.

You are right; the only way to pass the struct to the interrupt handler is through a static.

> I tried changing the argument to keyboard::init to &'static PS2Keyboard, which wants the controller to be static as well, but I can't pass the controller out of ps2_controller::init() as static.

If you look at the definition for [`PS2Keyboard`](https://github.com/theseus-os/Theseus/blob/639e30cc1e0c92e8dcaa33838d508705edb74a25/kernel/ps2/src/lib.rs#L399-L401):
```rust
pub struct PS2Keyboard<'c> {
    controller: &'c PS2Controller,
}
```
You'll see it's generic over a lifetime. This means that it can only live for as long as `'c`. If you were to expand the lifetime elisions in the signature of `keyboard::init`, it would look like this:
```rust
pub fn init<'a>(keyboard: PS2Keyboard<'a>, keyboard_queue_producer: Queue<Event>) -> Result<(), &'static str> {
    //
}
```
Now that means our `Once<PS2Keyboard<'a>>` can only live for `'a`. But our `Once<PS2Keyboard<'a>>` is stored in a static, so it must live for `'static`, and hence the `T` returned by `Once::call_once` must be `'static`.  Now, the error should make sense:
```
error: lifetime may not live long enough
  --> kernel/keyboard/src/lib.rs:53:27
   |
31 | pub fn init(keyboard: PS2Keyboard, keyboard_queue_producer: Queue<Event>) -> Result<(), &'static str> {
   |             -------- has type `PS2Keyboard<'a>`
...
53 |     KEYBOARD.call_once(|| keyboard);
   |                           ^^^^^^^^ returning this value requires that `'a` must outlive `'static`

error: could not compile `keyboard` due to previous error
```
Rust expects the closure to return something with a static lifetime but it returns something with a potentially shorter lifetime.

`Once<PS2Keyboard<'a>>: 'static` -> `PS2Keyboard<'a>: 'static` -> `'a: 'static`

This means the `keyboard::init` signature should look like so:
```rust
pub fn init(keyboard: PS2Keyboard<'static>, keyboard_queue_producer: Queue<Event>) -> Result<(), &'static str> {
    //
}
```

All this means the `PS2Keyboard` needs a static reference to the `PS2Controller`, which means the `PS2Controller` will also need to be stored in a static. After all, `PS2Keyboard` is just a wrapper around a `PS2Controller` and so you are indirectly passing the `PS2Controller` to the interrupt handler as well.

As a side note, it's probably best to name the lifetimes `'a` rather than `'c`.

2022-12-23 19:53 UTC, hecatia-elegua commented
@tsoutsman Thank you a lot!
Above I said the wrong thing. I tried `PS2Keyboard<'static>`, not `&'static PS2Keyboard`, oops. Maybe I did both at some point.
Still, that explained a bit more of what I was doing and helped my confidence.

Side note: I named them `'c` to point to it being the _controller's_ lifetime. Have seen some people put whole words in lifetimes, some people use a relevant first letter... I guess it's the same as with generics.

Now this works and all PS/2 crates save their respective struct in a static `Once<...>`. Would you want to review?

2022-12-25 14:13 UTC, tsoutsman requested changes
Mostly looks good. Just a couple of nitpicks.

2022-12-25 14:13 UTC, tsoutsman commented on kernel/ps2_controller/src/lib.rs
> +    static CONTROLLER: Once<PS2Controller> = Once::new();
Could you please move the static into the crate's root (like in `keyboard`)?

2022-12-25 14:13 UTC, tsoutsman commented on kernel/keyboard/src/lib.rs
>  ///    will push new keyboard events when a key action occurs.
Could you please update the docs?

2022-12-25 14:13 UTC, tsoutsman commented on kernel/keyboard/src/lib.rs
>  static KEYBOARD_PRODUCER: Once<Queue<Event>> = Once::new();
Could you please define a new struct `Keyboard` like so:
```rust
struct Keyboard {
    inner: PS2Keyboard,
    producer: Queue<Event>,
}
```
And then have a singular static? Generally speaking, the more statics, the worse because it can introduce race conditions, for example, if we were to add the ability to change keyboards while the operating system is running.

2022-12-25 14:13 UTC, tsoutsman commented on kernel/mouse/src/lib.rs
>  static MOUSE_PRODUCER: Once<Queue<Event>> = Once::new();
Similar thing to `keyboard`. Could you consolidate the statics, please?

2022-12-25 14:13 UTC, tsoutsman commented on kernel/ps2/src/lib.rs
> +    }
We can have a public static like so:
```rust
static PS2_CONTROLLER: PS2Controller = PS2Controller {
    data_port: Mutex::new(0x60),
    command_and_status_port: Mutex::new(0x64),
};
```
Then we can remove `PS2Controller::new` so that there are no concerns about it being called multiple times.

2022-12-25 14:13 UTC, tsoutsman commented on kernel/ps2/src/lib.rs
> +    /// The keyboard uses only [PS2_DATA_PORT].
This is a private const, so it won't show up in the docs.

```suggestion
    /// The keyboard only uses the data port.
```

2022-12-25 14:13 UTC, tsoutsman commented on kernel/ps2/src/lib.rs
> +    /// The mouse uses both [PS2_DATA_PORT] and [PS2_COMMAND_AND_STATUS_PORT].
This is a private const, so it won't show up in the docs.

```suggestion
    /// The mouse uses both the data, and command and status ports.
```

2022-12-25 14:13 UTC, tsoutsman commented on kernel/mouse/src/lib.rs
>  ///    will push new mouse events when a mouse action occurs.
Outdated.

2022-12-30 15:15 UTC, hecatia-elegua commented on kernel/ps2_controller/src/lib.rs
> +    static CONTROLLER: Once<PS2Controller> = Once::new();
I would like to put it into this crates root, but then your other suggestion in ps2 would either mean having two statics (one in ps2 and one here), or removing the one in ps2 but still using `PS2Controller::new`.

2023-01-02 13:57 UTC, tsoutsman commented on kernel/ps2_controller/src/lib.rs
> +    static CONTROLLER: Once<PS2Controller> = Once::new();
You're right. Since we're performing initialisation, we shouldn't have a default static. Can you just implement this suggestion then?

2023-01-02 17:38 UTC, hecatia-elegua commented
Done. Thank you for the review @tsoutsman!

2023-01-03 08:17 UTC, tsoutsman approved these changes

2023-01-03 08:28 UTC, merged

2023-01-03 08:29 UTC, tsoutsman commented
Looks good. Thank you.