Solve some warnings
theseus-os/Theseus pull request #783
Opened 2023-01-01 15:03 UTC by amab8901

Addresses https://github.com/theseus-os/Theseus/issues/526

idk which tasks in particular. I just solve all of them until there's nothing left.

2023-01-02 17:40 UTC, hecatia-elegua commented
You accidentally mixed in an unrelated commit 😉

2023-01-02 19:53 UTC, amab8901 commented
> You accidentally mixed in an unrelated commit wink

thanks, I solved it now

2023-01-02 21:29 UTC, hecatia-elegua requested changes
Good one! Thank you.
I left some comments for you and a few I have to ask others about.
The PR size is okay to me, as it's mostly plumbing.

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/ata/src/lib.rs
> +	fn is_empty(&self) -> bool { self.block_size() * self.size_in_blocks() == 0 }
```suggestion
	fn is_empty(&self) -> bool { self.len() == 0 }
```
It's silly to duplicate code for this, could you please also adjust all the other occurences?

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/external_unwind_info/src/lib.rs
> +        error!("External unwind info for {text_start:#X} was already registered"); ExternalUnwindInfoError::AlreadyExists
Please insert a newline after the semicolon here

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/frame_allocator/src/lib.rs
> +                    && !frame_is_in_list(&GENERAL_REGIONS.lock(), &end_frame)
Isn't this changing the semantics? Before, we locked once and passed a reference to that lock twice, now we lock twice. Might not matter, but someone else should review this one again.

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/fs_node/src/lib.rs
> +        self.len() == 0
nice, like this!

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/memfs/src/lib.rs
> +    pub fn new_fileref(name: String, parent: &DirRef) -> Result<FileRef, &'static str> {
Right, clippy wants `new` to always return `Self`, so you renamed it here.
I agree, maybe someone else would like to bikeshed on the naming.

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/memory/src/paging/table.rs
> +pub const P4: *mut Table<Level4> = 0o1_777_777_767_767_767_760_000 as *mut _;
The spacing actually had a point, but I know clippy screams at you about this and it doesn't really matter much.

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/memory_structs/src/lib.rs
> -            impl Into<usize> for $TypeName {
why the deletion?

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/path/src/lib.rs
> -                new_path.push_str(&format!("/{}",  component));
This seems like an oversight, you probably changed the above and thought this was doing the same, but it actually adds a `/` in front.

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/random/src/lib.rs
> +pub enum RandError {
For another reviewer: naming bikeshed

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/boot_info/src/multiboot2.rs
> +        multiboot2::MemoryArea::size(self) as usize == 0
Ok, the only other occurences are in this file, I think.

2023-01-02 21:29 UTC, hecatia-elegua commented on kernel/boot_info/src/uefi.rs
> +        self.len == 0
...and in this file

2023-01-09 02:02 UTC, kevinaboos requested changes
Thanks @amab8901! My thoughts are below:

Things I like and we should keep:
* `hpet`
* `apic`
* `crate_metadata_serde`
* `page_allocator`
* `pic`
* `tsc`

Things I'm conflicted about:
* the `is_empty()` lint makes sense collections-like data structures, but not for everything. 
  * IMO `KnownLength` shouldn't have an `is_empty()` function; please remove that.
  * Adding `is_empty()` to the `boot_info` stuff is fine and makes more sens there; though we ultimately won't use it.

Things I don't like (please revert):
* Changing `new` to something like `new_fileref` or `new_dirref`. 
* Changes to `kernel/memory/src/paging/table.rs`
* Changes to `kernel/memory_structs` -- this is incorrect
* Changes to all of the format strings, like `"/{component}` instead of `"{}", component`. Those aren't needed and do not always make it easier to read, please undo those.
* Undo everything in `kernel/random`; we need to deal with that separately.

2023-01-09 02:02 UTC, kevinaboos commented on kernel/memory_structs/src/lib.rs
> -            impl Into<usize> for $TypeName {
undo this

2023-01-09 02:02 UTC, kevinaboos commented on kernel/preemption/src/lib.rs
> +
undo

2023-01-09 02:02 UTC, kevinaboos commented on kernel/vfs_node/src/lib.rs
> +unsafe impl Sync for VFSDirectory {}
whoa, what's this? please undo

2023-01-09 02:02 UTC, kevinaboos commented on ports/theseus_std/src/os_str.rs
> +        self.len() == 0
this isn't better, please undo. Doesn't clippy itself state that you should use `is_empty()` instead of `len()` when available since it can be faster?

2023-01-09 02:02 UTC, kevinaboos commented on kernel/ata/src/lib.rs
> +	fn is_empty(&self) -> bool { self.len() == 0 }
remove

2023-01-09 02:02 UTC, kevinaboos commented on kernel/external_unwind_info/src/lib.rs
> +        error!("External unwind info for {text_start:#X} was already registered");
remove extra whitespace at end

2023-01-09 02:02 UTC, kevinaboos commented on kernel/external_unwind_info/src/lib.rs
> +}
add trailing new line to the end

2023-01-09 02:02 UTC, kevinaboos commented on kernel/gdt/src/lib.rs
> +             fmtr.write_fmt(format_args!("  {index}:  {entry:#016x}\n"))?;
undo

2023-01-09 02:02 UTC, kevinaboos commented on kernel/io/src/lib.rs
> +    fn is_empty(&self) -> bool;
remove

2023-01-09 06:45 UTC, kevinaboos requested changes
Mostly everything looks good; can you also undo the `new_fileref()` and `new_dirref()` changes? Then it'll be ready to merge, thanks!

2023-01-09 06:45 UTC, kevinaboos commented on kernel/io/src/lib.rs
> +    delegate!{ to self.0 { fn block_size(&self) -> usize; } }
remove trailing whitespace

2023-01-09 06:45 UTC, kevinaboos commented on kernel/memory/src/paging/table.rs
> +pub const P4: *mut Table<Level4> = 0o1_777_777_767_767_767_760_000 as *mut _;
please undo, this formatting is very specifically chosen to represent certain groupings of bits.

2023-01-09 11:26 UTC, kevinaboos approved these changes
Thanks for the many iterations of fixes! I bet future PRs will go quite smoothly now that you're used to the process.

2023-01-09 11:26 UTC, merged