Use new UEFI bootloader
theseus-os/Theseus pull request #792
Opened 2023-01-08 11:52 UTC by tsoutsman

The bootloader is at <https://github.com/theseus-os/uefi-bootloader>.

Depends on #785, #786, and #790. I haven't been able to properly review all the changes in this PR because it builds on top of many different PRs. Once they are merged, I'll be able to review it properly.

2023-01-08 11:55 UTC, tsoutsman commented on kernel/nano_core/src/asm/defines.asm
> +AP_GDT				equ TRAMPOLINE + 88
This shows up differently in my editor.

2023-01-09 02:43 UTC, kevinaboos commented
Thanks, I've reviewed all the PR this depends on and am ready to merge them pending some quick discussions.

2023-01-11 06:20 UTC, tsoutsman commented
Depends on #803.

2023-01-11 07:59 UTC, kevinaboos reviewed
Minor to-do: add a description of the `uefi_builder*` tool crates to the `tools/README.md` file

2023-01-11 07:59 UTC, kevinaboos commented on kernel/nano_core/src/asm/defines.asm
> +AP_GDT				equ TRAMPOLINE + 88
looks like you've used tabs instead of spaces

2023-01-11 07:59 UTC, kevinaboos commented on kernel/boot_info/src/lib.rs
> +    fn kernel_end(&self) -> Result<VirtualAddress, &'static str>;
fix doc comment above

2023-01-11 07:59 UTC, kevinaboos commented on kernel/boot_info/src/lib.rs
> +    /// Returns the section's length in memory.
is this comment addition intended to contrast against the section's length in the ELF file? if so, let's say that too.

2023-01-11 07:59 UTC, kevinaboos commented on kernel/nano_core/src/lib.rs
> +        type CaptainInitFunc = fn(MmiRef, NoDrop<EarlyIdentityMappedPages>, NoDrop<Stack>, VirtualAddress, VirtualAddress, VirtualAddress, Option<PhysicalAddress>) -> Result<(), &'static str>;
according to your other docs, the ap_gdt is a physical address

2023-01-11 07:59 UTC, kevinaboos commented on kernel/memory/src/lib.rs
> +                .translate(boot_info.kernel_end()?)
is this right? Looking at the calculation of `kernel_end`, it seems like an exclusive upper bound. I didn't dig into it in detail, but what happens if `kernel_end()` is aligned to the start of the next page, causing this `translate()` action to fail?

2023-01-11 07:59 UTC, kevinaboos commented on kernel/memory/src/lib.rs
> +                .translate(boot_info.kernel_end()?)
ok on second inspection, this is a bit odd. The boot_info provides the kernel end vaddr, which we then translate to physical, which we the use to obtain the identity vaddr? I legit cannot tell if that's equivalent to the previous code, lol

2023-01-11 07:59 UTC, kevinaboos commented on tools/uefi_builder/common/Cargo.toml
> +authors = ["Klim Tsoutsman <klim@tsoutsman.com>"]
please add a description (and in other Cargo.toml files too)

2023-01-11 08:07 UTC, kevinaboos requested changes

2023-01-11 08:07 UTC, kevinaboos commented on kernel/memory/src/paging/mapper.rs
> +pub fn translate(virtual_address: VirtualAddress) -> Option<PhysicalAddress> {
```suggestion
/// A convenience function to translate the given virtual address into a
/// physical address using the currently-active page table.
pub fn translate(virtual_address: VirtualAddress) -> Option<PhysicalAddress> {
```

2023-01-11 10:01 UTC, kevinaboos commented
LGTM; will approve & merge pending a review of `uefi-bootloader`

2023-01-12 03:41 UTC, kevinaboos approved these changes

2023-01-12 03:57 UTC, merged