Handle PS/2 better on real hardware
theseus-os/Theseus pull request #884
Opened 2023-03-16 13:47 UTC by hecatia-elegua

This is the second, actual PR (opposed to #870, which is just for debugging).

We still need to test on more real hardware, so this is a draft and still has some debug statements, which might be useful if early framebuffer logging is possible soon.
When everything works I can deduplicate all those loops as well.

2023-03-18 00:09 UTC, kevinaboos requested changes
Thanks so much! I'm happy to confirm that this PR makes the keyboard work on my real hw machine, as well as on QEMU and QEMU+KVM! Nice work.

The mouse still does not work on real hw, though it does work on QEMU and QEMU+KVM. Currently the only symptom I'm able to observe on real hw is that as soon as I move or click the mouse, the keyboard also stops working. This might be due to the myriad `loop`s you've inserted throughout the code, or just some other form of interference between the kbd and mouse w.r.t. shared ps2 data ports. We can discuss more here or on discord if you have other ideas to try. 

When you get a chance, can you clean up this PR to reduce the amount of verbose logging (or submit a different PR if you want to keep this as is)? Also be sure to remove an `loop`s inserted. After that, I'd be happy to merge it in, since it does at least allow the keyboard to work, which is must more important than the mouse.

Feel free to check out the latest changes to `theseus_main`, which enable a graphical framebuffer for early printing. It should work for you to get more info during early init more easily.

2023-03-18 00:09 UTC, kevinaboos commented on kernel/keyboard/src/lib.rs
> +    // - laptop 1 allows setting Scancode Set 2 and works
you have "laptop 1" written twice; i presume one of them is one laptop, and one is another? 

If you want to leave this comment in, it'd be best to provide as many details about the real hw as possible, e.g., by saying something like "A thinkpad X220 allows..."

2023-03-18 00:09 UTC, kevinaboos commented on kernel/ps2/src/lib.rs
> +    #[doc(hidden)]
it's a private fn, so this doesn't have any effect.

2023-03-18 00:09 UTC, kevinaboos commented on kernel/ps2/src/lib.rs
> +        //when doing command_to_keyboard, but it could also be caused by completely different things
if you merge in the latest changes from `theseus_main`, you should be able to disable the code routine that changes graphics mode when bringing up multiple CPUs. You can do that by commenting out this line: https://github.com/theseus-os/Theseus/blob/0f4f28ff86cf0be028ae5cdb6c36cbf2b2340fa7/kernel/multicore_bringup/src/lib.rs#L338

That way, the system will keep using the same framebuffer until the graphics/WM subsystem is initialized.

2023-03-18 12:29 UTC, hecatia-elegua commented
Should be good for merging now.

2023-03-20 18:02 UTC, kevinaboos approved these changes
Great, thanks a lot!

2023-03-20 18:03 UTC, merged