Add `sync::RwLock`
theseus-os/Theseus pull request #942
Opened 2023-04-23 00:53 UTC by tsoutsman

2023-04-26 00:22 UTC, kevinaboos commented
theseus-os/spin-rs#2 has been merge din

2023-04-26 01:59 UTC, tsoutsman commented
@kevinaboos should be ready.

2023-04-26 19:04 UTC, kevinaboos commented
> ~Should be ready.~
> 
> Nevermind.

Ok lmk when you'd like another review.

2023-05-08 11:04 UTC, tsoutsman commented
@kevinaboos should be ready.

2023-05-19 18:42 UTC, kevinaboos requested changes
Sorry for the delay, i left on vacation right before you readied this PR. 

Anyway, i like everything here, nice work!  One change request -- I think it'd be a good design choice to separate out the trait representing the flavor of actions for a Mutex from the trait representing the flavor of actions for an RwLock. There are a few reasons for this:
* I think it makes sense to separate them as they are typically implemented separately in both the std lib as well as crates like `spin`. 
* Also, some concrete impls of those flavor traits may not want to (or may not be able to) offer both a Mutex and an RwLock; separating them into two traits allows one to be implemented without the other, and is also a bit clearer imo.
* `RwLock<T>` typically has different Send/Sync bounds for its type `T` than `Mutex<T>` does. I realize this isn't part of the Flavor trait API, but it still speaks to the expectation of separation between the two.
* It would give the Flavor trait a more specific name: `MutexFlavor` and `RwLockFlavor`

2023-05-19 18:42 UTC, kevinaboos commented on libs/sync/src/lib.rs
> +    fn post_rw_lock_unlock(data: &Self::RwLockData, is_writer_or_last_reader: bool);
missing docs on these functions

2023-05-19 18:42 UTC, kevinaboos requested changes
Sorry for the delay, i left on vacation right before you readied this PR. 

Anyway, i like everything here, nice work!  One change request -- I think it'd be a good design choice to separate out the trait representing the flavor of actions for a Mutex from the trait representing the flavor of actions for an RwLock. There are a few reasons for this:
* I think it makes sense to separate them as they are typically implemented separately in both the std lib as well as crates like `spin`. 
* Also, some concrete impls of those flavor traits may not want to (or may not be able to) offer both a Mutex and an RwLock; separating them into two traits allows one to be implemented without the other, and is also a bit clearer imo.
* `RwLock<T>` typically has different Send/Sync bounds for its type `T` than `Mutex<T>` does. I realize this isn't part of the Flavor trait API, but it still speaks to the expectation of separation between the two.
* It would give the Flavor trait a more specific name: `MutexFlavor` and `RwLockFlavor`

2023-05-24 16:56 UTC, kevinaboos approved these changes
awesome work!

2023-05-24 17:00 UTC, merged