Add middle path for blocking mutex
theseus-os/Theseus pull request #968
Opened 2023-06-06 02:01 UTC by tsoutsman

Starting the task ID counters at 1 rather than 0 also lets us represent task IDs using NonZeroUsize permitting niche optimisations e.g. `Option<TaskId>` taking up as much space as a `usize`. This would however involve some unsafe and even if we do decide to implement it, is better left for another PR.

2023-06-06 02:02 UTC, tsoutsman commented
I left the `log::warn` in there so that when we switch to using `sync_block` we can make sure that the problematic interleaving is in fact incredibly rare. After that we can remove it.

2023-06-06 05:44 UTC, tsoutsman commented
Closes #576.

2023-06-09 18:10 UTC, kevinaboos requested changes
after more consideration and study, i think this is a good approach. I left a few small comments.

2023-06-09 18:10 UTC, kevinaboos commented on kernel/sync_block/src/lib.rs
> +        if let Some(holder_task) = task::get_task(holder_id).and_then(|task| task.upgrade()) {
we can make this conditional short-circuit to false if the holder_id is `0`.  (not valid syntax unless let-chains now support this)
```rust
if holder_id != 0 && let Some(holder_task) = task::get_task(holder_id).and_then(|task| task.upgrade()) {
```

2023-06-09 18:10 UTC, kevinaboos commented on kernel/sync_block/src/lib.rs
> +
shall we try the fast path again here before blocking this task, considering that we just executed a series of "long-running" operations above as part of the middle path? I think so.

In other words, the lock may have been released whilst we were running `data.holder.load()` and `task::get_task(holder_id).and_then(|task| task.upgrade())`, so we can try to grab it before sleeping here.

2023-06-09 18:10 UTC, kevinaboos commented on kernel/sync_block/src/lib.rs
> +            while holder_task.running_on_cpu().is_some()
if you just want to know whether it's running, you can use this
```suggestion
            while holder_task.is_running()
```

2023-06-09 18:10 UTC, kevinaboos commented on kernel/sync_block/src/lib.rs
> +
actually yeah, this works, all you need to do is move L91-93 to here instead such that it runs unconditionally after the middle path attempt.

2023-06-11 17:43 UTC, kevinaboos approved these changes

2023-06-11 17:50 UTC, merged