Use `interrupt_controller` in `interrupts::aarch64`
theseus-os/Theseus pull request #972
Opened 2023-06-13 15:49 UTC by NathanRoyer

Changes:
- `BOARD_CONFIG` becomes const so that I can reference it in other consts
- `BOARD_CONFIG` now contains board-specific interrupt numbers
- `interrupt_controller`'s initializer is called from captain
- `interrupt_controller::InterruptDestination` no longer contains a local_number on aarch64
- `interrupt_controller::send_ipi` allows sending to AllButMe
- new `interrupt_controller::InterruptNumber` enum, wrapping Local/SystemInterruptNumber
- aarch64-specific `interrupt_controller::init_secondary_cpu_interface`; panics on x86_64 (documented)
- don't enable timer/shootdown/pl011 interrupts from `interrupts::init` as they're enabled later

2023-06-13 17:19 UTC, NathanRoyer commented
todo: implement Binary, Octal, LowerHex, UpperHex for *InterruptNumber

2023-06-13 17:20 UTC, NathanRoyer commented
Convert get_int_ctlr to a private util method

2023-07-05 18:01 UTC, NathanRoyer commented
This PR is paused until we find a way to represent both x86's interrupt numbers (a u8) and Arm GIC's interrupt number types (local peripheral, IPI, shared peripheral)

2023-07-19 19:42 UTC, kevinaboos requested changes
looks decent, i left a few small comments. Also there is a conflict that needs to be resolved.

2023-07-19 19:42 UTC, kevinaboos commented on kernel/interrupt_controller/src/lib.rs
> +    init,
what's this for?

2023-07-19 19:42 UTC, kevinaboos commented on kernel/interrupt_controller/src/aarch64.rs
> +    fn send_ipi(&self, num: InterruptNumber, dest: Option<CpuId>) {
why did this function's parameters change? It seemed to be good previously -- the `InterruptDestination` type is much clearer than `Option<CpuId>`. 

It's not clear (and also surprising, especially without documentation) that passing in `dest = None` sends the IPI to all other CPUs. Seems like we should just use the `InterruptDestination` enum.

2023-07-19 19:42 UTC, kevinaboos commented on kernel/interrupt_controller/src/x86_64.rs
>      /// Initializes the interrupt controller, on aarch64
indentation issue here

2023-07-20 15:33 UTC, NathanRoyer commented on kernel/interrupt_controller/src/lib.rs
> +    init,
This re-exposes the init function, which is called from captain

2023-07-20 15:34 UTC, NathanRoyer commented on kernel/interrupt_controller/src/aarch64.rs
> +    fn send_ipi(&self, num: InterruptNumber, dest: Option<CpuId>) {
It was a wrapping struct before, but an enum would be better indeed. I'll see if I can do that

2023-07-20 19:07 UTC, kevinaboos commented on kernel/interrupt_controller/src/lib.rs
> +    init,
ah ok, nevermind, my github display was confusing. All good.

2023-08-01 19:13 UTC, kevinaboos approved these changes

2023-08-01 19:21 UTC, merged