Add priority inheritance for blocking mutex
theseus-os/Theseus pull request #985
Opened 2023-06-22 04:37 UTC by tsoutsman

The code duplication across `runqueue_epoch` and `runqueue_priority` is temporary before we refactor schedulers and runqueues to not use `cfg` blocks.

2023-06-26 20:41 UTC, kevinaboos commented
all dependency PRs have been merged in now :+1:

2023-06-27 00:20 UTC, tsoutsman commented
Should be good to merge.

2023-06-27 18:31 UTC, kevinaboos requested changes
Looks good overall, just left one suggestion about using a guard-like type to ensure priority inheritance gets undone even in the case of a panic.

2023-06-27 18:31 UTC, kevinaboos commented on kernel/sync_block/src/lib.rs
> +            let deinherit_priority = scheduler::inherit_priority(&holder_task);
This is a nice design for undoing the effects of priority inheritance. It'd be even nicer to use a guard type such that the effects of priority inheritance can also be undone in the case of exceptional execution (unwinding after a panic). Should be easy enough to wrap up the returned closure in a struct that implements `Drop` too.

2023-06-28 17:16 UTC, kevinaboos approved these changes

2023-06-28 17:20 UTC, merged