Add `graphic` and `terminal` options to Makefile
theseus-os/Theseus pull request #986
Opened 2023-06-23 12:18 UTC by tsoutsman

`graphic=no` adds the `-nographic` flag to the QEMU invocation. Supporting this required a few changes to `captain`.

`terminal=(name of terminal)` e.g. `terminal=alacritty` will launch a new terminal window connected to `SERIAL2`. We do this by testing the next free TTY with `tools/free_tty` and assuming QEMU will use the same TTY. This may seem jank, but I think it's the only feasible solution.

I've tested this on MacOS (side note: macOS makes it very hard to launch a new terminal window from the terminal) so if someone could test this on Linux as well that would be good. Also, I wasn't able to build for `aarch64` so the changes to `captain` need to be tested to ensure builds for `aarch64` didn't break.

2023-06-27 19:46 UTC, kevinaboos requested changes
Looks good. A few minor points:
1. The name `free_tty` could be misinterpreted as freeing (releasing) a TTY, so I'd vote changing it to something more specific like `available_tty` or `get_tty`.
2. Can we use `cargo run` to invoke the tty getter application, or does that interfere with the `fork()` call therein? If possible, I'd prefer that as it makes the makefile dependency set cleaner.

Two general comments:
* I wonder if there is a proper way is to actually obtain the QEMU-created PTY from  QEMU itself. That'd be nice.
* Do we always want "nographic" specifically? I'm unsure if that will interfere with our `mon:stdio` settings.

2023-06-27 19:46 UTC, kevinaboos commented on kernel/captain/src/lib.rs
> +    #[cfg(not(target_arch = "x86_64"))]
nit: prefer aarch64 instead of not x86 for clarity

2023-06-27 19:46 UTC, kevinaboos commented on Makefile
> +# The slee is to give QEMU time to create the TTY.
typo

2023-06-27 19:46 UTC, kevinaboos commented on Makefile
> +# The slee is to give QEMU time to create the TTY.
typo

2023-06-27 19:46 UTC, kevinaboos commented on kernel/captain/src/lib.rs
> +        Err(error) => info!("Window manager initialisation failure: {error}"),
might want to mention that this is expected if nographic was specified.

2023-06-28 04:20 UTC, tsoutsman commented
> - I wonder if there is a proper way is to actually obtain the QEMU-created PTY from QEMU itself. That'd be nice.

I'm pretty sure there isn't aside from grepping the output but that is non-trivial since it's a stream and we still want to display it to the user.

> - Do we always want "nographic" specifically? I'm unsure if that will interfere with our mon:stdio settings.

It shouldn't. The only thing `nographic` option changes is that the VGA text mode is redirected to stdio as well.

2023-06-28 19:37 UTC, kevinaboos commented
> The only thing `nographic` option changes is that the VGA text mode is redirected to stdio as well.

I see that from the QEMU manual, however it doesn't actually do that on my system -- i see no graphical output, even when forcing VGA text mode. Nbd, doesn't matter. It's also worth nothing that `nographic` doesn't remove the VGA device, so Theseus still sees and uses it. So it's not truly headless yet, it just hides the graphical window even though Theseus is still rendering content there. This is okay for now since we don't actually yet support true headless operation where graphics doesn't exist, but it'd be easy to account for that possibility in the captain during initialization.

2023-06-28 19:41 UTC, kevinaboos approved these changes

2023-06-28 19:48 UTC, merged